### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by axmav** [janpf/self-supervised-multi-task-aesthetic-pretraining#3]
Hello! Could you provide some instructions of how to train and test your solution?
Also pretrained model file is not available (link not active).
Thank you!

**Comment by janpf** [comment]
The train, test and evaluation scripts are uploaded. Of course you'd first have to pretrain (train_pre) and then finetune (train_fine). I did not create any bashscripts at the time. All argparse arguments should be easily matchable to configs listed in the papers.
Also all AVA related code is based on the referenced NIMA repo, so train, test and evaluation should be checked there.

I believe the link fell victim to some password length policy. I've updated it.
