### ISSUE TITLE
Incomplete program

### ISSUE THREAD

**Issue by dikapiliao1** [janpf/self-supervised-multi-task-aesthetic-pretraining#4]
There is no ‘SimCLR’ and 'RotNet' in 'relatedWorks' package, but you referenced the code in 'relatedWorks/tune_related/NIMA.py'

**Comment by janpf** [comment]
For both I used the repos listed in the readme. I used their code to pretrain with the only change being the dataloader and then just used the given code to finetune those resulting models.
