### ISSUE TITLE
Can you share your pretrained models/backbones?

### ISSUE THREAD

**Issue by ducanhnguyen-lab** [janpf/self-supervised-multi-task-aesthetic-pretraining#7]
thanks for your work!

**Comment by janpf** [comment]
Sure, they are available under the link in the Readme.
I think the access got reset after some time but I just refreshed it :)

**Comment by MinhNguyenHuu1** [comment]
@janpf Can you share the checkpoint trained by self-supervised learning with pexels dataset?
