### ISSUE TITLE
How to speed up darktable? It is very slow.

### ISSUE THREAD

**Issue by ducanhnguyen-lab** [janpf/self-supervised-multi-task-aesthetic-pretraining#8]
about 1.7s for  `subprocess.run(["darktable-cli", img_path, edit_file, edited_img_path, "--core", "--library", ":memory:"])`

**Comment by janpf** [comment]
Hi!

yes, sadly it is very slow. We **heavily** parallelized (read: ~500 instances of darktable running at the same time) the image generation on our compute cluster and implemented reading and writing straight from and to ramdisks, redis,...

Nevertheless the image preprocessing took if I remember correctly a few (?) weeks :/

If I had to do it again I would personally not use darktables for this, but a native image library for python, like kornia, PIL, opencv,...
They might not have a few of the transformations but they should be waaay faster, even fast enough to be able to transform the images on the fly without any need of saving pretransformed images to the harddisk.
